require('dotenv').config();
const pino=require('pino');const readline=require('readline');const qrcode=require('qrcode-terminal');const {default:makeWASocket,useMultiFileAuthState,DisconnectReason,fetchLatestBaileysVersion}=require('baileys');const {Boom}=require('@hapi/boom');
const db=require('./lib/database');const {loadPlugins}=require('./lib/pluginLoader');const {handleAirbotGroupMessage}=require('./lib/airbotBridge');const {jidPhone,getText,getQuotedMessage}=require('./lib/utils');const {startVotingScheduler,sendPoll}=require('./lib/votingScheduler');const {startWebsiteMonitor}=require('./lib/websiteMonitor');const {askGemini}=require('./lib/gemini');
const prefix=process.env.PREFIX||'/';const loginMethod=String(process.env.LOGIN_METHOD||'pairing').toLowerCase();const owner=String(process.env.OWNER_NUMBER||'').replace(/\D/g,'');const configuredOwnerLids=String(process.env.OWNER_LID||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=>x.includes('@lid')?x:x+'@lid');const autoRead=String(process.env.AUTO_READ||'false').toLowerCase()==='true';let schedulerStarted=false;
function ask(q){const rl=readline.createInterface({input:process.stdin,output:process.stdout});return new Promise(r=>rl.question(q,a=>{rl.close();r(a)}))}
function isGroup(jid=''){return jid.endsWith('@g.us')}
async function resolveSenderIdentity(sock,msg){const key=msg?.key||{};const candidates=[key.participantPn,key.senderPn,key.participantAlt,key.remoteJidAlt,key.participant,key.remoteJid].filter(Boolean);const phones=[];const lids=candidates.filter(j=>String(j).includes('@lid')).map(String);for(const jid of candidates){if(String(jid).includes('@s.whatsapp.net'))phones.push(jidPhone(jid))}for(const jid of candidates){if(!String(jid).includes('@lid'))continue;try{let pn=await sock.signalRepository?.lidMapping?.getPNForLID?.(jid);if(!pn){const lid=String(jid).split('@')[0];pn=await sock.signalRepository?.lidMapping?.getPNForLID?.(lid)}if(pn)phones.push(jidPhone(pn))}catch(e){console.error('[LID RESOLVE]',e.message)}}const unique=[...new Set(phones.filter(Boolean))];return {phone:unique[0]||'',phones:unique,lids,candidates}}
async function shouldAiReply(sock,msg,body){const chat=msg.key.remoteJid;if(!isGroup(chat))return true;const info=msg.message?.extendedTextMessage?.contextInfo||msg.message?.imageMessage?.contextInfo||msg.message?.videoMessage?.contextInfo||{};const me=sock.user?.id?.split(':')[0]?.split('@')[0]||'';const mentioned=(info.mentionedJid||[]).some(j=>jidPhone(j)===me);const repliedToBot=!!getQuotedMessage(msg)&&jidPhone(info.participant||'')===me;return mentioned||repliedToBot}
async function start(){const {state,saveCreds}=await useMultiFileAuthState('./sessions');const {version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,auth:state,logger:pino({level:'silent'}),printQRInTerminal:false,browser:['SCARD-BOT','Chrome','1.0.0']});sock.ev.on('creds.update',saveCreds);
if(!state.creds.registered&&loginMethod==='pairing'){let number=String(process.env.PAIRING_NUMBER||'').replace(/\D/g,'');if(!number)number=String(await ask('Masukkan nomor WhatsApp (628xxx): ')).replace(/\D/g,'');setTimeout(async()=>{try{const code=await sock.requestPairingCode(number);console.log('\n🔑 PAIRING CODE:',code.match(/.{1,4}/g)?.join('-')||code,'\n')}catch(e){console.error('Gagal membuat pairing code:',e.message)}},1500)}
sock.ev.on('connection.update',u=>{if(!state.creds.registered&&loginMethod==='qr'&&u.qr){console.log('\n📱 Scan QR berikut dari WhatsApp > Perangkat tertaut > Tautkan perangkat:\n');qrcode.generate(u.qr,{small:true})}if(u.connection==='open'){console.log('✅ SCARD-BOT terhubung. AUTO_READ =',autoRead);if(!schedulerStarted){schedulerStarted=true;startVotingScheduler(sock);startWebsiteMonitor(sock);if(String(process.env.VOTING_TEST_ON_START||'false').toLowerCase()==='true'){const key='voting:startup-test';if(!db.wasSent(key)){setTimeout(async()=>{try{console.log('[VOTING STARTUP TEST] sending...');await sendPoll(sock,'TEST VOTING');db.markSent(key);console.log('[VOTING STARTUP TEST] success')}catch(e){console.error('[VOTING STARTUP TEST ERROR]',e)}},3000)}else console.log('[VOTING STARTUP TEST] already sent, skip')}}}if(u.connection==='close'){const code=new Boom(u.lastDisconnect?.error)?.output?.statusCode;if(code!==DisconnectReason.loggedOut){console.log('Koneksi putus, reconnect...');setTimeout(start,2000)}else console.log('Session logout. Hapus folder sessions lalu login ulang dengan metode '+loginMethod+'.')}});
sock.ev.on('messages.upsert',async u=>{for(const msg of u.messages||[]){try{if(!msg.message)continue;const chat=msg.key.remoteJid;if(!chat||chat==='status@broadcast')continue;if(!msg.key.fromMe&&await handleAirbotGroupMessage(sock,msg))continue;if(autoRead)await sock.readMessages([msg.key]).catch(()=>{});const body=getText(msg).trim();console.log('[RX]',msg.key.fromMe?'SELF':'IN',chat,'body=',JSON.stringify(body));const ident=await resolveSenderIdentity(sock,msg);let phone=ident.phone;let user=phone?db.getUser(phone):null;const selfPhone=jidPhone(sock.user?.id||'');const selfMessage=!!msg.key.fromMe;if(!user){for(const p of ident.phones){const found=db.getUser(p);if(found){phone=p;user=found;break}}}const ownerLids=[...new Set([...configuredOwnerLids,...db.getSetting('ownerLids',[])])];let isOwner=selfMessage||(owner&&selfPhone===owner)||ident.phones.includes(owner)||phone===owner||user?.role==='owner'||ident.lids.some(l=>ownerLids.includes(l));if(!isOwner&&owner&&ident.lids.length&&ident.phones.includes(owner)){isOwner=true;db.setSetting('ownerLids',[...new Set([...ownerLids,...ident.lids])])}if(isOwner){if(ident.lids.length){const saved=db.getSetting('ownerLids',[]);const merged=[...new Set([...saved,...ident.lids])];if(merged.length!==saved.length)db.setSetting('ownerLids',merged)}console.log('[AUTH] OWNER matched',phone||ident.lids[0])}else if(ident.lids.length&&!user)console.log('[AUTH] unresolved/unregistered sender jid=',ident.lids[0],'pn=',ident.phones.join(',')||'-','alt=',msg.key.participantAlt||msg.key.remoteJidAlt||'-');
if(body){const plugins=loadPlugins();const prefixed=body.startsWith(prefix)||body.startsWith('.');const raw=(prefixed?body.slice(1):body).trim();const [c,...args]=raw.split(/\s+/);const command=String(c||'').toLowerCase();const plugin=plugins.find(p=>p.commands.includes(command));console.log('[COMMAND]',command,'plugin=',plugin?.file||'-','owner=',isOwner,'registered=',!!user);if(plugin){if(plugin.registered!==false&&!user&&!isOwner){console.log('[AUTH] blocked registered command',command,'jid=',ident.lids[0]||ident.candidates[0]||'-');continue}if(plugin.ownerOnly&&!isOwner){console.log('[AUTH] blocked owner command',command,'jid=',ident.lids[0]||ident.candidates[0]||'-');continue}const reply=text=>sock.sendMessage(chat,{text:String(text)},{quoted:msg});try{console.log('[PLUGIN] run',plugin.file);await plugin.run({sock,msg,reply,command,args,text:args.join(' '),phone:phone||owner||selfPhone,user,isOwner,db});console.log('[PLUGIN] done',plugin.file)}catch(e){console.error('[PLUGIN ERROR]',plugin.file,e);await reply('❌ Command gagal: '+String(e?.message||e)).catch(()=>{})}continue}if(prefixed)continue}
if(selfMessage)continue;if((!user&&!isOwner)||!db.getSetting('aiEnabled',false)||!body)continue;if(!(await shouldAiReply(sock,msg,body)))continue;try{await sock.sendPresenceUpdate('composing',chat).catch(()=>{});const clean=body.replace(/@\d+/g,'').trim()||body;const answer=await askGemini(clean);if(answer)await sock.sendMessage(chat,{text:answer},{quoted:msg})}catch(e){console.error('[GEMINI]',e.message)}finally{await sock.sendPresenceUpdate('paused',chat).catch(()=>{})}
}catch(e){console.error('[MESSAGE ERROR]',e)}}})}
start().catch(console.error);
