require('dotenv').config();
const pino=require('pino');const readline=require('readline');const {default:makeWASocket,useMultiFileAuthState,DisconnectReason,fetchLatestBaileysVersion}=require('baileys');const {Boom}=require('@hapi/boom');
const db=require('./lib/database');const {loadPlugins}=require('./lib/pluginLoader');const {jidPhone,getText,getQuotedMessage}=require('./lib/utils');const {startVotingScheduler}=require('./lib/votingScheduler');const {askGemini}=require('./lib/gemini');
const prefix=process.env.PREFIX||'/';const owner=String(process.env.OWNER_NUMBER||'').replace(/\D/g,'');const autoRead=String(process.env.AUTO_READ||'false').toLowerCase()==='true';let schedulerStarted=false;
function ask(q){const rl=readline.createInterface({input:process.stdin,output:process.stdout});return new Promise(r=>rl.question(q,a=>{rl.close();r(a)}))}
function isGroup(jid=''){return jid.endsWith('@g.us')}
async function shouldAiReply(sock,msg,body){const chat=msg.key.remoteJid;if(!isGroup(chat))return true;const info=msg.message?.extendedTextMessage?.contextInfo||msg.message?.imageMessage?.contextInfo||msg.message?.videoMessage?.contextInfo||{};const me=sock.user?.id?.split(':')[0]?.split('@')[0]||'';const mentioned=(info.mentionedJid||[]).some(j=>jidPhone(j)===me);const repliedToBot=!!getQuotedMessage(msg)&&jidPhone(info.participant||'')===me;return mentioned||repliedToBot}
async function start(){const {state,saveCreds}=await useMultiFileAuthState('./sessions');const {version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,auth:state,logger:pino({level:'silent'}),printQRInTerminal:false,browser:['SCARD-BOT','Chrome','1.0.0']});sock.ev.on('creds.update',saveCreds);
if(!state.creds.registered){let number=String(process.env.PAIRING_NUMBER||'').replace(/\D/g,'');if(!number)number=String(await ask('Masukkan nomor WhatsApp (628xxx): ')).replace(/\D/g,'');setTimeout(async()=>{try{const code=await sock.requestPairingCode(number);console.log('\nPAIRING CODE:',code.match(/.{1,4}/g)?.join('-')||code,'\n')}catch(e){console.error('Gagal membuat pairing code:',e.message)}},1500)}
sock.ev.on('connection.update',u=>{if(u.connection==='open'){console.log('✅ SCARD-BOT terhubung. AUTO_READ =',autoRead);if(!schedulerStarted){schedulerStarted=true;startVotingScheduler(sock)}}if(u.connection==='close'){const code=new Boom(u.lastDisconnect?.error)?.output?.statusCode;if(code!==DisconnectReason.loggedOut){console.log('Koneksi putus, reconnect...');setTimeout(start,2000)}else console.log('Session logout. Hapus folder sessions lalu pairing ulang.')}});
sock.ev.on('messages.upsert',async u=>{for(const msg of u.messages||[]){try{if(!msg.message||msg.key.fromMe)continue;const chat=msg.key.remoteJid;if(!chat||chat==='status@broadcast')continue;if(autoRead)await sock.readMessages([msg.key]).catch(()=>{});const body=getText(msg).trim();const phone=jidPhone(msg.key.participant||msg.key.remoteJid);const user=db.getUser(phone);const isOwner=phone===owner||user?.role==='owner';
if(body.startsWith(prefix)){const raw=body.slice(prefix.length).trim();if(!raw)continue;const [c,...args]=raw.split(/\s+/);const command=c.toLowerCase();const plugin=loadPlugins().find(p=>p.commands.includes(command));if(!plugin)continue;if(plugin.registered!==false&&!user)continue;if(plugin.ownerOnly&&!isOwner)continue;const reply=text=>sock.sendMessage(chat,{text:String(text)},{quoted:msg});await plugin.run({sock,msg,reply,command,args,text:args.join(' '),phone,user,isOwner,db});continue}
if(!user||!db.getSetting('aiEnabled',false)||!body)continue;if(!(await shouldAiReply(sock,msg,body)))continue;try{await sock.sendPresenceUpdate('composing',chat).catch(()=>{});const clean=body.replace(/@\d+/g,'').trim()||body;const answer=await askGemini(clean);if(answer)await sock.sendMessage(chat,{text:answer},{quoted:msg})}catch(e){console.error('[GEMINI]',e.message)}finally{await sock.sendPresenceUpdate('paused',chat).catch(()=>{})}
}catch(e){console.error('[MESSAGE ERROR]',e)}}})}
start().catch(console.error);
